version: "3"

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressUser
      MYSQL_PASSWORD: wordpressPass
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - 8082:8080

  wordpress:
    image: wordpress:5.5.1-php7.4-apache
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpressUser
      WORDPRESS_DB_PASSWORD: wordpressPass
      WORDPRESS_DB_NAME: wordpress
    ports:
      - 8081:80
    volumes:
      - ./wordpress/plugins:/var/www/html/wp-content/plugins
      - ./wordpress/themes:/var/www/html/wp-content/themes

  gatsby:
    build: ./gatsby
    ports: 
      - 8080:8000
    volumes:
      - ./gatsby:/app
      - /app/node_modules
      - /app/.cache
