version: "3"

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - 8082:8080

  wordpress:
    image: wordpress:5.5.1-php7.4-apache
    ports:
      - 8081:80
    volumes:
      - ./wordpess/plugins:/var/www/html/wp-content/plugins
      - ./wordpess/themes:/var/www/html/wp-content/themes

  gatsby:
    build: ./gatsby
    ports: 
      - 8080:8000
    volumes:
      - ./gatsby:/app
